export default {
    SAVE_SELECTEDCHANNEL: 'SAVE_SELECTEDCHANNEL',
    SAVE_SELECTEDCHANNELINDEX: 'SAVE_SELECTEDCHANNELINDEX',
    SAVE_SELECTEDTRACK: 'SAVE_SELECTEDTRACK',
    SAVE_SELECTEDTRACKINDEX: 'SAVE_SELECTEDTRACKINDEX',
    SAVE_SOUNDOBJECT: 'SAVE_SOUNDOBJECT',
    SAVE_MYCHANNELS: 'SAVE_MYCHANNELS',
    SAVE_PLAYSTATE: 'SAVE_PLAYSTATE',
    SAVE_PROFILE: 'SAVE_PROFILE',
};
